// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJUMDQikvr-WTVDhu0dgOSn3GzKb_cVBM',
    appId: '1:329825818663:ios:f4cf5fce08699444fad602',
    messagingSenderId: '329825818663',
    projectId: 'posget',
    storageBucket: 'posget.firebasestorage.app',
    iosClientId: '329825818663-47rpiqfskk4gofu93veu2sfql3d2js78.apps.googleusercontent.com',
    iosBundleId: 'com.example.postgetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJUMDQikvr-WTVDhu0dgOSn3GzKb_cVBM',
    appId: '1:329825818663:ios:f4cf5fce08699444fad602',
    messagingSenderId: '329825818663',
    projectId: 'posget',
    storageBucket: 'posget.firebasestorage.app',
    iosClientId: '329825818663-47rpiqfskk4gofu93veu2sfql3d2js78.apps.googleusercontent.com',
    iosBundleId: 'com.example.postgetx',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1UOLJnLAQjk2K1dJwm3TWD4UpyNJChFE',
    appId: '1:329825818663:web:efa77ae450004b30fad602',
    messagingSenderId: '329825818663',
    projectId: 'posget',
    authDomain: 'posget.firebaseapp.com',
    storageBucket: 'posget.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGfIUiu3hV0Eli9Yhl31hovdvcTtkAIs',
    appId: '1:329825818663:android:7928e2d42f558b33fad602',
    messagingSenderId: '329825818663',
    projectId: 'posget',
    storageBucket: 'posget.firebasestorage.app',
  );

}